<?php

/**
 * Implements hook_entity_info().
 */
function rating_system_entity_info() {
  $return = array(
    'rating_formula' => array(
      'label' => t('Rating formula'),
      'plural label' => t('Rating formulas'),
      'description' => t('A Rating formula'),
      'entity class' => 'RatingFormula',
      'controller class' => 'EntityAPIControllerExportable',
      'views controller class' => 'EntityDefaultViewsController',
      'base table' => 'rating_formula',
      'exportable' => TRUE,
        'module' => 'rating_system',
      'entity keys' => array(
        'id' => 'rgid',
        'name' => 'name',
        'label' => 'label',
      ),
      'admin ui' => array(
        'path' => 'admin/structure/rating-system/rating-formulas',
        'file' => 'rating_system.rating_formula.admin.inc',
      ),
      'access callback' => 'rating_formula_access',
      'access arguments' => array('administer rating formulas'),
    ),
  );

  return $return;
}

/**
 * Access callback.
 */
function rating_formula_access($permission) {
  return user_access($permission);
}

/**
 * Implements hook_field_extra_fields().
 * Declare our extra fields to the field UI
 */
function rating_system_field_extra_fields() {
  $rating_formulas = rating_formula_load();

  if ($rating_formulas) {
    foreach ($rating_formulas as $rating_formula) {
      $extra[$rating_formula->entity_type][$rating_formula->entity_bundle] = array(
        'display' => array(
          'rating_system_' . $rating_formula->name => array(
            'label' => $rating_formula->label . ' ' . t('(Rating system)'),
            'weight' => 0,
          ),
        )
      );
    }

    return $extra;
  }
}

/**
 * Implements hook_entity_view_alter().
 * Attach our extra fields to the display.
 */
function rating_system_entity_view_alter(&$build, $type) {
  if ($type != 'rating_formula') {
    $rating_formulas = rating_formula_load_multiple_by_entity_type_and_bundle($type, $build['#bundle']);
    if ($rating_formulas) {
      foreach ($rating_formulas as $rating_formula) {
        // Attach our extra field.
        $build['rating_system_' . $rating_formula->name] = array(
          '#type' => 'markup',
          '#markup' => '<span>' . $rating_formula->label . '</span>'
        );
      }
    }
  }  
}

/**
 * Implements hook_permission().
 */
function rating_system_permission() {
  return array(
    'administer rating formulas' =>  array(
      'title' => t('Administer rating formulas'),
      'description' => t('Administer rating formulas'),
    ),
  );
}

/**
 * Use a separate class for Rating formulas so we can specify some defaults
 * modules may alter.
 */
class RatingFormula extends Entity {

  /**
   * Returns whether the Rating formula is locked, thus may not be deleted or renamed.
   *
   * Rating formulas provided in code are automatically treated as locked, as well
   * as any fixed Rating formula.
   */
  public function isLocked() {
    return isset($this->status) && empty($this->is_new) && (($this->status & ENTITY_IN_CODE) || ($this->status & ENTITY_FIXED));
  }
}

/**
* Gets an array of all Rating formulas, keyed by the type name.
*
* @param $mixed
*   May be a formula name.
* @return RatingFormula[]
*   Depending whether $type isset, an array of Rating formulas or a single one.
*/
function rating_formula_load($rating_formula_name = NULL) {
  $rating_formulas = entity_load_multiple_by_name('rating_formula', isset($rating_formula_name) ? array($rating_formula_name) : FALSE);
  return isset($rating_formula_name) ? reset($rating_formulas) : $rating_formulas;
}

/**
* Gets an array of all Rating formulas, keyed by the type name.
*
* @param $entity_type
*   Entity type.
* @param $entity_bundle
*   Entity bundle.
* @return RatingFormula[]
*   Depending whether $type isset, an array of Rating formulas or a single one.
*/
function rating_formula_load_multiple_by_entity_type_and_bundle($entity_type = NULL, $entity_bundle = NULL) {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'rating_formula');
  if ($entity_type) { $query->propertyCondition('entity_type', $entity_type); }
  if ($entity_bundle) { $query->propertyCondition('entity_bundle', $entity_bundle); }
  $query->addMetaData('account', user_load(1)); // Run the query as user 1.
  $result = $query->execute();

  $rating_formula_ids = array_keys($result['rating_formula']);
  $rating_formulas = entity_load('rating_formula', $rating_formula_ids);

  return $rating_formulas;
}
