<?php
/**
* @file
* The main file for the rating system module.
*
* Here we include all the other files.
*/

include_once('rating_system.crud.inc');
include_once('rating_system.score.inc');
include_once('rating_system.display.inc');

/**
 * Access callback.
 */
function rating_formula_access($permission) {
  return user_access($permission);
}

/**
 * Implements hook_permission().
 */
function rating_system_permission() {
  return array(
    'administer rating formulas' =>  array(
      'title' => t('Administer rating formulas'),
      'description' => t('Administer rating formulas'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function rating_system_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'rating_system') . '/includes/views',
  );
}
